#define AS_ID_DEFAULT 0
#define AS_ID_HEAD 1
#define AS_ID_ARM_SIDES 2
#define AS_ID_ARM_TOP 3
#define AS_ID_TORSO_SIDES 4
#define AS_ID_TORSO_TOP 5
#define AS_ID_TORSO_FRONT 6
#define AS_ID_LEG_SIDES 7
#define AS_ID_LEG_TOP 8