name: Call of Chaos
version: '0.0.4-2'
author: Back Burner
description: COC
minecraft: 1.19

pipeline:
  - mecha
  - beet.contrib.copy_files

require:
  - bolt
  - bolt_expressions
  - plugins.nbt_literals
  - beet.contrib.lantern_load.base_data_pack
  - beet.contrib.worldgen
  - plugins.update_lang


data_pack:
  name: Call of Chaos
  load:
    - .
  render:
    functions:
      - coc:*


resource_pack:
  name: Call of Chaos [RP]
  load:
    - .

output: '__dist__'

meta:
  bolt_expressions:
    init_path: 'technical/init'
  copy_files:
    data_pack: 
     data/coc/item_groups: data/coc/item_groups