name: Call of Chaos
version: '0.2.0'
author: Back Burner
description: COC
minecraft: "1.21"

pipeline:
  # Makes sure items are processed prior to Mecha running
  - plugins.smithed.pipeline
  - mecha
  - beet.contrib.unknown_files
  - plugins.generate_rift_circles

require:
  - plugins.smithed
  - bolt
  - weld_deps
  - mecha.contrib.raw
  - plugins.nbt_literals
  - beet.contrib.lantern_load.base_data_pack
  - plugins.livelyreload

data_pack:
  name: Call of Chaos
  pack_format: 60
  load:
    - .

resource_pack:
  name: Call of Chaos [RP]
  pack_format: 45
  load:
    - .
    - dependencies/shaders

output: '__dist__'

meta:
  bolt: 
    prelude: 
      - "smithed:items/prelude"
      - "coc:prelude"

  coc:
    debug: true

  weld_deps:
    deps:
      crafter: "0.4.2"
      custom-block: "0.4.2"

  lsp:
    excluded_plugins:
      - plugins.livelyreload