name: Call of Chaos
version: '0.2.0'
author: Back Burner
description: COC
minecraft: "1.21"

pipeline:
  - mecha
  - beet.contrib.copy_files
  - plugins.completed

require:
  - weld_deps
  - mecha.contrib.raw
  - plugins.smithed
  - bolt
  - bolt_expressions
  - bolt_expressions.contrib.commands
  - plugins.nbt_literals
  - beet.contrib.lantern_load.base_data_pack
  - plugins.update_lang

data_pack:
  name: Call of Chaos
  load:
    - .
  render:
    functions:
      - coc:*


resource_pack:
  name: Call of Chaos [RP]
  load:
    - .

output: '__dist__'

meta:
  bolt_expressions:
    init_path: 'technical/init'
  copy_files:
    data_pack: 
     data/coc/item_groups: data/coc/item_groups

  weld_deps:
    deps:
      crafter: "0.4.2"
      custom-block: "0.4.2"
